// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line index.qtpl:1
package templates

//line index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line index.qtpl:1
func StreamIndexPage(qw422016 *qt422016.Writer, white, red, green, blue float64) {
//line index.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LED strip controller</title>
    <script>
        function updateTextInput(id, val) {
            document.getElementById(id).value = val;
        }

        function post(path, params, method) {
            method = method || "post";

            var form = document.createElement("form");
            form.setAttribute("method", method);
            form.setAttribute("action", path);

            for (var key in params) {
                if (params.hasOwnProperty(key)) {
                    var hiddenField = document.createElement("input");
                    hiddenField.setAttribute("type", "hidden");
                    hiddenField.setAttribute("name", key);
                    hiddenField.setAttribute("value", params[key]);

                    form.appendChild(hiddenField);
                }
            }

            document.body.appendChild(form);
            form.submit();
        }

        function sendRequest() {
            post("/", {
                white: document.getElementById("ch1").value,
                red: document.getElementById("ch2").value,
                green: document.getElementById("ch3").value,
                blue: document.getElementById("ch4").value,
            }, "post")
        }
    </script>
</head>
<body>
<datalist id="tickmarks">
    <option value="0" label="0%">
    <option value="10">
    <option value="20">
    <option value="30">
    <option value="40">
    <option value="50" label="50%">
    <option value="60">
    <option value="70">
    <option value="80">
    <option value="90">
    <option value="100" label="100%">
</datalist>
<form action="" method="post">
    <p>
        <label for="ch1">White</label><br>
        <input type="range" id="ch1" name="white" value="`)
//line index.qtpl:61
	qw422016.N().D(int(white))
//line index.qtpl:61
	qw422016.N().S(`" min="0" max="100" onchange="sendRequest()"
               list="tickmarks">
    </p>
    <p>
        <label for="ch2">Red</label><br>
        <input type="range" id="ch2" name="red" value="`)
//line index.qtpl:66
	qw422016.N().D(int(red))
//line index.qtpl:66
	qw422016.N().S(`" min="0" max="100" onchange="sendRequest()"
               list="tickmarks">
    </p>
    <p>
        <label for="ch3">Green</label><br>
        <input type="range" id="ch3" name="green" value="`)
//line index.qtpl:71
	qw422016.N().D(int(green))
//line index.qtpl:71
	qw422016.N().S(`" min="0" max="100" onchange="sendRequest()"
               list="tickmarks">
    </p>
    <p>
        <label for="ch4">Blue</label><br>
        <input type="range" id="ch4" name="blue" value="`)
//line index.qtpl:76
	qw422016.N().D(int(blue))
//line index.qtpl:76
	qw422016.N().S(`" min="0" max="100" onchange="sendRequest()"
               list="tickmarks">
    </p>
    <p>
        <input type="submit">
    </p>
</form>
</body>
</html>
`)
//line index.qtpl:85
}

//line index.qtpl:85
func WriteIndexPage(qq422016 qtio422016.Writer, white, red, green, blue float64) {
//line index.qtpl:85
	qw422016 := qt422016.AcquireWriter(qq422016)
//line index.qtpl:85
	StreamIndexPage(qw422016, white, red, green, blue)
//line index.qtpl:85
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:85
}

//line index.qtpl:85
func IndexPage(white, red, green, blue float64) string {
//line index.qtpl:85
	qb422016 := qt422016.AcquireByteBuffer()
//line index.qtpl:85
	WriteIndexPage(qb422016, white, red, green, blue)
//line index.qtpl:85
	qs422016 := string(qb422016.B)
//line index.qtpl:85
	qt422016.ReleaseByteBuffer(qb422016)
//line index.qtpl:85
	return qs422016
//line index.qtpl:85
}
